source 'https://rubygems.org'

# 🎯 ObjectVersion 70 support - FORCED LATEST VERSION
gem 'cocoapods', '~> 1.16.2'
gem 'xcodeproj', :git => 'https://github.com/CocoaPods/Xcodeproj.git', :branch => 'master'
